
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: max
  labels:
    app: react01-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react01-front
  template:
    metadata:
      labels:
        app: react01-front
    spec:
      containers:
      - name: test
        image: nginx
        ports:
        - containerPort: 3000
